### ISSUE TITLE
Extension open a popup on page load

### ISSUE THREAD

**Issue by jifeon** [FarLauren/-_-#4]
Please fix it, I want to open popup only when I click on the button. Opening on page load is really annoying!

**Comment by maZahaca** [comment]
Yep

**Comment by FarLauren** [comment]
you want too much :D, i'll fix it when understand how @jifeon

**Comment by jifeon** [comment]
hey! what the progress here? Are there some estimations?

**Comment by maZahaca** [comment]
We need it yesterday :) ahahahah
